version: '3'

services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    restart: always
    volumes:
      - ./sessions:/app/.wwebjs_auth
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge 